TP_WEB/Controllers/FormationAcademiquesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_WEB.Models;

namespace TP_WEB.Controllers
{
    public class FormationAcademiquesController : Controller
    {
        private readonly SiteContext _context;

        public FormationAcademiquesController(SiteContext context)
        {
            _context = context;
        }

        // GET: FormationAcademiques
        public async Task<IActionResult> Index()
        {
              return _context.FormationAcademiques != null ? 
                          View(await _context.FormationAcademiques.ToListAsync()) :
                          Problem("Entity set 'SiteContext.FormationAcademiques'  is null.");
        }

        // GET: FormationAcademiques/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.FormationAcademiques == null)
            {
                return NotFound();
            }

            var formationAcademique = await _context.FormationAcademiques
                .FirstOrDefaultAsync(m => m.ID == id);
            if (formationAcademique == null)
            {
                return NotFound();
            }

            return View(formationAcademique);
        }

        [Authorize(Roles = "Administrateur")]
        // GET: FormationAcademiques/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FormationAcademiques/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrateur")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,NomEcole,ProgrammeEtude,AnneeDebutFormation,AnneeFinFormation,LienProgrammeEtude,EstDiplomeObtenu")] FormationAcademique formationAcademique)
        {
            if (ModelState.IsValid)
            {
                _context.Add(formationAcademique);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(formationAcademique);
        }

        [Authorize(Roles = "Administrateur")]
        // GET: FormationAcademiques/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.FormationAcademiques == null)
            {
                return NotFound();
            }

            var formationAcademique = await _context.FormationAcademiques.FindAsync(id);
            if (formationAcademique == null)
            {
                return NotFound();
            }
            return View(formationAcademique);
        }

        // POST: FormationAcademiques/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrateur")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,NomEcole,ProgrammeEtude,AnneeDebutFormation,AnneeFinFormation,LienProgrammeEtude,EstDiplomeObtenu")] FormationAcademique formationAcademique)
        {
            if (id != formationAcademique.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(formationAcademique);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormationAcademiqueExists(formationAcademique.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(formationAcademique);
        }

        [Authorize(Roles = "Administrateur")]
        // GET: FormationAcademiques/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.FormationAcademiques == null)
            {
                return NotFound();
            }

            var formationAcademique = await _context.FormationAcademiques
                .FirstOrDefaultAsync(m => m.ID == id);
            if (formationAcademique == null)
            {
                return NotFound();
            }

            return View(formationAcademique);
        }

        [Authorize(Roles = "Administrateur")]
        // POST: FormationAcademiques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.FormationAcademiques == null)
            {
                return Problem("Entity set 'SiteContext.FormationAcademiques'  is null.");
            }
            var formationAcademique = await _context.FormationAcademiques.FindAsync(id);
            if (formationAcademique != null)
            {
                _context.FormationAcademiques.Remove(formationAcademique);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormationAcademiqueExists(int id)
        {
          return (_context.FormationAcademiques?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

TP_WEB/Controllers/PortfoliosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_WEB.Models;

namespace TP_WEB.Controllers
{
    public class PortfoliosController : Controller
    {
        private readonly SiteContext _context;

        public PortfoliosController(SiteContext context)
        {
            _context = context;
        }

        // GET: Portfolios
        public async Task<IActionResult> Index()
        {
            return _context.Portfolios != null ?
                    View(await _context.Portfolios.Include(p => p.Image).ToListAsync()) :
                    Problem("Entity  set 'siteContext.Portfolios' is null.");
        }

        // GET: Portfolios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Portfolios == null)
            {
                return NotFound();
            }

            var portfolio = await _context.Portfolios
                .Include(p => p.Image)
                .FirstOrDefaultAsync(p => p.ID == id);
            if (portfolio == null)
            {
                return NotFound();
            }

            return View(portfolio);
        }

        [Authorize(Roles = "Administrateur")]
        // GET: Portfolios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Portfolios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrateur")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,NomProjet,DescriptionProjet,TypeProjet,ImageID,TechnologieUtilise,NombreHeure,AdresseWeb,RoleProjet,Afficher")] Portfolio portfolio)
        {
            if (ModelState.IsValid)
            {
                if(Request.Form.Files.Count > 0) 
                { 
                    var file = Request.Form.Files.SingleOrDefault();

                    Image img = new Image()
                    {
                        NomImage = file!.FileName,
                        ContentType = file!.ContentType
                    };

                    MemoryStream stream = new MemoryStream();
                    file.CopyTo(stream);

                    img.ImageData = stream.ToArray();
                    stream.Close();
                    stream.Dispose();

                    _context.Add(img);
                    await _context.SaveChangesAsync();

                    portfolio.ImageID = img.Id;
                }
                _context.Add(portfolio);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(portfolio);
        }

        [Authorize(Roles = "Administrateur")]
        // GET: Portfolios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Portfolios == null)
            {
                return NotFound();
            }


            var portfolio = await _context.Portfolios.FindAsync(id);
            if (portfolio == null) 
            {
                return NotFound();
            }

            return View(portfolio);
        }

        // POST: Portfolios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrateur")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,NomProjet,DescriptionProjet,TypeProjet,ImageID,TechnologieUtilise,NombreHeure,AdresseWeb,RoleProjet,Afficher")] Portfolio portfolio)
        {
            if (id != portfolio.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(portfolio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortfolioExists(portfolio.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(portfolio);
        }

        [Authorize(Roles = "Administrateur")]
        // GET: Portfolios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Portfolios == null)
            {
                return NotFound();
            }

            var portfolio = await _context.Portfolios
                .Include(p => p.Image)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (portfolio == null)
            {
                return NotFound();
            }

            return View(portfolio);
        }

        // POST: Portfolios/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrateur")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Portfolios == null)
            {
                return Problem("Entity set 'SiteContext.Portfolios'  is null.");
            }
            var portfolio = await _context.Portfolios.FindAsync(id);
            if (portfolio != null)
            {
                _context.Portfolios.Remove(portfolio);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PortfolioExists(int id)
        {
          return (_context.Portfolios?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

TP_WEB/Views/Shared/ÀPropos.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8" name="viewport" />
    <title>MouhammadWDiouf</title>
    <link rel="stylesheet" href="/css/normalize.css" />
    <link rel="stylesheet" href="/css/style2.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap"
          rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap"
          rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Ultra&display=swap"
          rel="stylesheet" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <script src="https://kit.fontawesome.com/6fa5dbff09.js"
            crossorigin="anonymous"></script>
    <script defer src="/js/script.js" defer></script>
</head>

<body>
    <!-- Moi -->
    <section class="histoire">
        <div class="wrapper">
            <div class="histoires"
                 data-aos="fade-up-right"
                 data-aos-duration="3000">
                <div class="infosHistoires">
                    <h1>Mon Histoire</h1>
                    <p>
                        Bonjour, Moi c’est Mouhammad Wagane Diouf et j’ai 21 ans. Je me
                        décris comme étant une personne ambitieuse, sérieuse, humble et
                        déterminé. Ce que j’aime le plus c’est réfléchir et régler des
                        problèmes. C’est pourquoi j’adore la programmation, celle-ci me
                        permet d'allier réflexion, création et résolution de problème.
                    </p>
                </div>
                <img src="/images/WaganeOrdi.jpg" alt="Photo_Mouhammad" />
            </div>

            <!-- Écoles Secondaire -->
            <div class="histoires" data-aos="fade-up-left" data-aos-duration="3000">
                <img src="/images/logo-ecole-secondaire-mgr-a-m-parent.png"
                     alt="logo-ecole-secondaire-mgr-am-parent" />
                <div class="infosHistoires">
                    <p>
                        Au secondaire, je suis allé à l'école secondaire
                        <strong>Monseigneur-Parent.</strong> Ayant déjà un faible pour les
                        technologies et les mathématiques, je suis entré dans
                        <strong> concentration Science et Technologies.</strong> C’est
                        dans ces années où j'ai créé mon premier jeu vidéo GameMaker et
                        mes premiers photomontages.
                    </p>
                </div>
            </div>

            <!-- Cégep Edouard Montpetit -->
            <div class="histoires"
                 data-aos="fade-up-right"
                 data-aos-duration="3000">
                <div class="infosHistoires">
                    <p>
                        J'ai ensuite décider d'aller au cégep
                        <strong>Édouard-Montpetit</strong> en
                        <strong> technique d’intégration en multimédia.</strong> J'ai
                        suivi ce programme pendant <strong>2 ans</strong> , et à la fin de
                        la 2e année, j'ai pu constater que le multimédia n'était pas
                        exactement ce que je recherchais.
                    </p>
                </div>
                <img src="/images/WaganeGoodVibes.JPG" alt="Photo_Mouhammad" />
            </div>

            <!-- Cégep Saint Jean Sur Richelieu -->
            <div class="histoires" data-aos="fade-up-left" data-aos-duration="3000">
                <img src="/images/infos.jpeg"
                     alt="logo-ecole-secondaire-mgr-am-parent" />
                <div class="infosHistoires">
                    <p>
                        Finalement, me voici en
                        <strong>technique de l'informatique</strong> au cégep
                        <strong>Saint-Jean-Sur-Richelieu</strong>. Je suis actuellement en
                        première année de ce programme et j'ai trouvé ma vocation. Je
                        souhaite grandir dans cette profession en tant que futur
                        programmeur et entrepreneur.
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section class="En-Résumé" data-aos="fade-up" data-aos-duration="3000">     
        <div class="quiSuisJe">
            <div class="wrapper">
                <h1>Quels sont mes atouts ?</h1>
                <div class="cards">
                    <div class="card">
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="flip-card-front">
                                    <h2>?</h2>
                                </div>
                                <div class="flip-card-back">
                                    <h1>Ambitieux</h1>
                                    <p>
                                        J'ai des ambitions très haute, j'ai des objectifs à long
                                        termes très haute.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="flip-card-front">
                                    <h2>?</h2>
                                </div>
                                <div class="flip-card-back">
                                    <h1>Sérieux</h1>
                                    <p>
                                        Au moment de travailler sur un projet j'essaie toujours
                                        d'être le plus professionnel possible.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="flip-card-front">
                                    <h2>?</h2>
                                </div>
                                <div class="flip-card-back">
                                    <h1>Humble</h1>
                                    <p>Je n'aime pas vanter les projets que je réalise.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="flip-card-front">
                                    <h2>?</h2>
                                </div>
                                <div class="flip-card-back">
                                    <h1>Déterminé</h1>
                                    <p>
                                        Lorsque je dis que je vais faire quelque chose cela peut
                                        prendre du temps, mais je le ferais.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="Objectifs" data-aos="zoom-in-up" data-aos-duration="1000">
        <div class="wrapper">
            <div class="contentObjectif">
                <h1>Mes futurs objectifs</h1>
                <p>
                    Pour mon futur stage je souhaite pour un début travailler en tant
                    que technicien informatique. je souhaite acquérir des compétences
                    qui me permettrons de me familiariser dans ce millieu. Ensuite je
                    souhaiterais travailler en temps que développeur web pour au final
                    travailler en temps que développeur freelance.
                </p>
            </div>
        </div>
    </section>
    <script>AOS.init();</script>
</body>
</html>

TP_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/normalize.css" />
    <link rel="stylesheet" href="/css/style2.css" />
    <title>@ViewData["Title"] - TP_WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TP_WEB.styles.css" asp-append-version="true" />
</head>
<body class="A-Propos">
  
    <!--    Made by Erik Terwan    -->
    <!--   24th of November 2015   -->
    <!--        MIT License        -->
    <nav role="navigation">
        <div id="menuToggle">
            <!--
        A fake / hidden checkbox is used as click reciever,
        so you can use the :checked selector on it.
        -->
            <input type="checkbox" />

            <!--
        Some spans to act as a hamburger.

        They are acting like a real hamburger,
        not that McDonalds stuff.
        -->
            <span></span>
            <span></span>
            <span></span>

            <!--
        Too bad the menu has to be inside of the button
        but hey, it's pure CSS magic.
        -->
            <ul id="menu">
                <a asp-action="Index" asp-controller="Home" asp-area="">
                    <li>Acceuil</li>
                </a>
                   
                <a asp-action="A_propos" asp-controller="Home" asp-area="">  
                    <li>À Propos</li>
                </a>

                <a asp-action="Index" asp-controller="ExperienceProfessionels" asp-area="">
                    <li>Expérience Professionel</li>
                </a>

                <a asp-action="Index" asp-controller="FormationAcademiques" asp-area="">
                    <li>Formation Académique</li>
                </a>

                <a asp-action="Index" asp-controller="Portfolios" asp-area="">
                    <li>Mes Projets</li></a>

                <a asp-action="Contact" asp-controller="Home" asp-area="">    
                    <li>Contact</li>
                </a>

                <partial name="_LoginPartial"/>
            </ul>
            
        </div>
    </nav>
  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>